#! /usr/bin/python
'''
 *  $Id: JobOpt_Hex2Root, 2015-03-07 15:52:31 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. EQM
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import os
import DMPSW                    # Load DAMPE software
import libDmpHex2Root as Hex2Root

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.SetEventNumber(200)     #  default: -1
#DMPSW.Core.StartTime("2013-01-01 00:00:00")     # default: 2013-01-01 00:00:00
#DMPSW.Core.StopTime("2016-01-01 00:00:00")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info
#DMPSW.Core.LogHeader("On")        # default: Off

#-------------------------------------------------------------------
# RootIOSvc Service
#DMPSW.RootIOSvc.SetInputPath(os.environ["DMPSWWORK"]+"/run/BT/sci")
DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141118_214521.frd")
#DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141117_135210.frd")
DMPSW.RootIOSvc.SetOutputFile("tesx.root")
DMPSW.RootIOSvc.SetWriteList("Event/Rdc")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = Hex2Root.DmpAlgHex2Root()
rdcAlgBT.SetMode("EQM")
#rdcAlgBT.SetConnector("Psd",DMPSW.WorkPath+"/share/Connector/Psd/EQM")
#rdcAlgBT.SetConnector("Bgo",DMPSW.WorkPath+"/share/Connector/Bgo/EQM")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


