#! /usr/bin/python
'''
 *  $Id: JobOpt_Hex2Root, 2014-11-06 13:47:56 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. EQM
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import os
import DMPSW                    # Load DAMPE software
import libDmpHex2Root as Hex2Root

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.MaxEventNumber("4")     #  default: -1 
#DMPSW.Core.StartTime("2013-01-01 00:00:00")     # default: 2013-01-01 00:00:00
#DMPSW.Core.StopTime("2016-01-01 00:00:00")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info
#DMPSW.Core.LogHeader("On")        # default: Off

#-------------------------------------------------------------------
# RootIOSvc Service
DMPSW.RootIOSvc.InputPath(os.environ["DMPSWWORK"]+"/run/BT/sci")
DMPSW.RootIOSvc.InputFile("A2_20141024_181906.frd")
#DMPSW.RootIOSvc.OutputPath(os.environ["DMPSWWORK"]+"/run/BT/raw")
DMPSW.RootIOSvc.WriteList("Event/Rdc")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = Hex2Root.DmpAlgHex2Root()
rdcAlgBT.SetConnector("Psd",DMPSW.WorkPath+"/share/Connector/Psd/EQM")
rdcAlgBT.SetConnector("Bgo",DMPSW.WorkPath+"/share/Connector/Bgo/EQM")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


