#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdcEQM, 2014-09-10 12:46:00 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. EQM
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpRdcEQM as RdcEQM

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.Set("EventNumber","305")     # If NOT set
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Debug")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.
#DMPSW.Core.Set("LogHeader","On")

#-------------------------------------------------------------------
# RootIOSvc Service
DMPSW.RootIOSvc.Set("OutData/WriteList","Event/Rdc/EventHeader;Event/Rdc/Bgo")  # split by ;
#DMPSW.RootIOSvc.Set("OutData/Path","./Rdc2/xx")

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = RdcEQM.DmpAlgRdcEQM()
#rdcAlgBT.Set("Psd/Connector","Psd/EQM")
#rdcAlgBT.Set("Stk/Connector",Stk/EQM")
rdcAlgBT.Set("Bgo/Connector","Bgo/EQM")
#rdcAlgBT.Set("Nud/Connector","Nud/EQM")
rdcAlgBT.Set("BinaryFile","A2_20140912_092040.frd")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


